MauroDataMapper/mdm-core

mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/UrlMappings.groovy
mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemController.groovy
mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemInterceptor.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemService.groovy
mdm-core/grails-app/views/treeItem/ancestors.gson
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/tree/TreeItemFunctionalSpec.groovy

The endpoint works its way up from the provided catalogue item till it reaches the top of the tree then wraps
all the proceding objects in the top level container.
changes were made to the tree item controller, service, gson view and functional spec.
Some JDOC explanation has been provided for the recursive implementation because it could be unclear

Added TreeItem Endpoint addition to show under the /ancestors option

---

mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelController.groovy

- Return empty 200 status from /federate endpoint to prevent UI error when subscribing to model
- This makes the 'Synchronise' button in the UI not do anything (previously errored)
- To be reviewed as part of MC-9726

Temporarily disable subscribed model federate endpoint

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/admin/ApiPropertyService.groovy
mdm-plugin-profile/build.gradle

Don't use the gradle asset pipeline plugin, so don't generate an empty assets `manifest.properties` file, which causes asset loading to barf in some circumstances

Don't generate an empty asset manifest file for mdm-plugin-profile (Solves #185)

---

mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/facet/Metadata.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/MetadataService.groovy
mdm-plugin-profile/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/profile/ProfileFunctionalSpec.groovy

Closes #180 
Add optional filtering by namespace, key and value to queries used when retrieving metadata.
This enables the endpoint ```/dataModels/${id}/profiles/otherMetadata``` to be used, for example, as follows:
```/dataModels/${id}/profiles/otherMetadata?ns=mynamespace&key=mykey&value=myvalue```

gh-180 add filtering by namespace (ns), key and value

---

mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/DataTypeService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/provider/importer/DataModelJsonImporterServiceSpec.groovy

Closes #205 and also closes https://metadatacatalogue.myjetbrains.com/youtrack/issue/MC-9536
This change adds SummaryMetadata and SummaryMetadataReport to the facets which are propagated when a Data Model (and also Data Class, Data Element and Data Type) is imported with the 'Propagate Facets' flag set.

gh-205 propagate SummaryMetadata

---

mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/Model.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelServiceIntegrationSpec.groovy

Closes #206 
Fixes a bug which caused a method getting the latest version of a finalised model to return the wrong result when the latest version was >= 10. This meant that importing a model after version 10.0.0 would fail.

Feature/gh 206 Fix retrieval of latest version of finalised model

---

mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/DataTypeService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/test/provider/DataBindDataModelImporterProviderServiceSpec.groovy

Closes #208 
When importing a Data Model, the BreadCrumb tree is set for Enumeration Values.

Feature/gh 208 Set the domainId for a BreadcrumbTree on Enumeration Value

---

mdm-plugin-datamodel/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementController.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/DataTypeService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelServiceIntegrationSpec.groovy
mdm-plugin-datamodel/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/traits/service/SummaryMetadataAwareService.groovy

Closes #70 
On New Version and New Branch, ensure that Summary Metadata against Data Model, Data Class, Data Element and Data Type is copied to the new model(s).

Feature/gh 70 - Copy Summary Metadata to new model version

---

mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueController.groovy
mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueInterceptor.groovy
mdm-plugin-federation/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/federation/UrlMappings.groovy
mdm-plugin-federation/grails-app/views/subscribedCatalogue/show_min.gson
mdm-plugin-federation/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueFunctionalSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/federation/SubscribedCatalogueFunctionalSpec.groovy

- Move subscribed catalogue admin actions under /admin URL
- Update subscribed catalogue functional tests

Separate subscribed catalogue admin endpoints

---

mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
mdm-plugin-profile/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/profile/ProfileFunctionalSpec.groovy
mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/provider/DynamicJsonProfileProviderService.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/profile/ProfileFunctionalSpec.groovy

- Fix the way profiles are sorted, so that when a profile having two versions, each with version tags, is retrieved by namespace and name only, the most recent semantic version is retrieved.
- Exclude non-finalised dynamic profiles from the profiles listed at the ```/{multiFacetAwareItemDomainType}/{multiFacetAwareItemId}/profiles/used``` and ```/{multiFacetAwareItemDomainType}/{multiFacetAwareItemId}/profiles/unused``` endpoints

Feature/gh 209 - fix profile sort

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/email/EmailService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/EditService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/service/AnonymisableService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/service/DomainService.groovy
mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedCatalogueService.groovy
mdm-plugin-federation/grails-app/services/uk/ac/ox/softeng/maurodatamapper/federation/SubscribedModelService.groovy
mdm-plugin-federation/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/federation/test/BaseSubscribedModelServiceIntegrationSpec.groovy
mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/CatalogueUserController.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/CatalogueUserService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/authentication/ApiKeyService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/role/SecurableResourceGroupRoleService.groovy
mdm-security/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/security/role/SecurableResourceGroupRoleServiceIntegrationSpec.groovy
mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/CatalogueUserControllerSpec.groovy
mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/CatalogueUserServiceSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/security/CatalogueUserFunctionalSpec.groovy

Support the anonymisation of a CatalogueUser by:
- Adding an AnonymisableService which must be implemented by all services which handle any data that may require to be anonymised in future. Each service must implement the ```anonymise``` method in a way relevant for that service.
- Implementing the ```anonymise``` method for all DomainServices, plus other core services which do not implement DomainService.
- Changing the endpoint which deletes a Catalogue User so that when the query parameter ```?permanent=true``` is specified (i.e. ```DELETE api/catalogueUsers/{catalogueUserId}?permanent=true```) then anonymisation occurs. Without this parameter, the default behaviour of simply marking the user's disabled flag is retained.
In most cases the anonymisation is done by updating the email …

Feature/mc 9577 - CatalogueUser anonymisation

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/email/EmailService.groovy

When sending emails, plugins may wish to use API Properties which are specific to the plugin, rather than being defined in the ApiPropertyEnum.
This PR adds a method sendEmailToUser with relevant API Property keys passed as strings rather than ApiPropertyEnum.

mc-9777 sendEmailToUser when not using ApiPropertyEnum

---

mdm-plugin-datamodel/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementController.groovy
mdm-plugin-datamodel/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/DataTypeController.groovy
mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/ModelDataType.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/DataTypeService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/ModelDataTypeService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementFunctionalSpec.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/item/datatype/DataTypeFunctionalSpec.groovy
mdm-testing-functional/grails-app/conf/application.yml

* Allow POST to DataTypes without a label for RTs and MDTs
* Generate a default label of "Reference to X" where X is the label of the reference
* Confirm the existence of the reference
* If a DT already exists with that default label then generate a new one with the next number in order suffixed
* Allow POST to DataElements without a label in the DataType for creating new DTs alongside the DE
* Use the default label for RTs and MDTs when creating a DE if no label supplied
* Try and find existing DT with same domaintype and label when creating a DE and DT at the same time.
If the DT exists then use that one rather than creating a new one which will fail as the DT already exists

mc-9808 Allow a simplified creation for ReferenceTypes and ModelDataTypes

---

mdm-core/README.md
mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/UrlMappings.groovy
mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/session/SessionController.groovy
mdm-core/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/core/provider/MauroDataMapperServiceProviderServiceSpec.groovy
mdm-core/src/integration-test/resources/url-mappings/tracked_endpoints.txt
mdm-plugin-datamodel/README.md
mdm-plugin-datamodel/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelController.groovy
mdm-plugin-datamodel/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/datamodel/UrlMappings.groovy
mdm-plugin-datamodel/src/integration-test/resources/url-mappings/tracked_endpoints.txt
mdm-plugin-referencedata/README.md
mdm-plugin-referencedata/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/referencedata/ReferenceDataModelController.groovy
mdm-plugin-referencedata/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/referencedata/UrlMappings.groovy
mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/ReferenceDataModelServiceIntegrationSpec.groovy
mdm-plugin-referencedata/src/integration-test/resources/url-mappings/tracked_endpoints.txt
mdm-plugin-terminology/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/terminology/TerminologyServiceIntegrationSpec.groovy
mdm-testing-functional/README.md
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/versionedfolder/container/VersionedFolderFunctionalSpec.groovy
mdm-testing-functional/untested_endpoints.md

- Remove unused clean datatypes/dataclasses endpoints from datamodel and referencedata plugins (resolves #272)
- Remove unused keep alive endpoint (resolves #259)
Also:
- Ensure tests use assertions where needed

Clean up unused endpoints

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/email/EmailService.groovy

Adds a method to send an email to a user. The properties map is provided by the caller of this method, so that an external plugin can specify its own email body and its own properties map.

mc-9827 add method to send email with any properties map

---

mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy
mdm-plugin-datamodel/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassServiceSpec.groovy

When adding missing Reference Type Data Classes, copy the hierarchy of Data Classes containing the Reference Type.
Make a small change to the way Semantic Links are copied.
Closes #269

Feature/gh 269 - Copy Data Class hierarchy for Reference Types

---

mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy

Fix a "StaleStateException" by flushing each save of target class and data element

gh-295 flush when saving data class and data element in the subset operation

---

mdm-common/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/version/Version.groovy
mdm-common/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/version/VersionSpec.groovy
mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy
mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/UrlMappings.groovy
mdm-plugin-profile/grails-app/init/uk/ac/ox/softeng/maurodatamapper/profile/BootStrap.groovy
mdm-plugin-profile/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/ProfileService.groovy
mdm-plugin-profile/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/profile/ProfileFunctionalSpec.groovy
mdm-plugin-profile/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/profile/object/JsonProfileSpec.groovy
mdm-plugin-profile/src/integration-test/resources/url-mappings/tracked_endpoints.txt
mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/domain/ConfigurableProfileFieldTypes.groovy
mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/domain/ProfileFieldDataType.groovy
mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/domain/ProfileSection.groovy
mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/object/Profile.groovy
mdm-testing-functional/grails-app/services/uk/ac/ox/softeng/maurodatamapper/profile/InvalidProfileService.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/profile/ProfileFunctionalSpec.groovy
mdm-testing-functional/src/main/resources/InvalidProfile.json

- Treat custom datatypes in profiles as strings (resolves #213)
- Fix to loading date formats from ApiProperties (resolves #290)
- Use finalised dynamic profile as default version (resolves #292), restrict dynamic profiles to finalised only in profile providers endpoint, sort profile provider endpoints
- Show only latest versions (by metadata namespace) of unused profiles by default, add latest versions (by metadata namespace) param to unused and used profile endpoints

Profile datatype fixes and restrict dynamic profile endpoints to finalised versions

---

mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy

Check against the top-level path item, rather than the immediate parent.  Solves #278 where the models are in different folders inside the VF

Import Data Elements into Data Classes within the same VF

---

mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/profile/ProfileFunctionalSpec.groovy

No functional changes.
Adds tests to verify that the existing endpoints for bulk editing of profiles on data elements work for:
- terms of a terminology
- data types of a data model
- data class and child data class of a data model

gh-329 test bulk edit of profiles for terms

---

mdm-plugin-referencedata/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueController.groovy
mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueFunctionalSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/referencedata/ReferenceDataValueFunctionalSpec.groovy

Closes #274
- Update functional tests, removing `referenceDataModel` from the body of each test, which has the effect of creating a failing test for the scenario described in the ticket
- Override the `createResource`method so that we can set the referenceDataModel using the ID from the URL, rather than wrongly expecting it to be in the body of the request

gh-274 set referenceDataModel from URL

---

mdm-plugin-terminology/grails-app/services/uk/ac/ox/softeng/maurodatamapper/terminology/TerminologyService.groovy
mdm-plugin-terminology/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/terminology/TerminologyServiceIntegrationSpec.groovy

This PR adds the functionality to batch-save multiple terminologies at the same time.  The existing batch-save works on a single terminology, which brings a big speed improvement for a single terminology with many terms, but this new service method brings the same speed improvement when saving many small terminologies.

Batch save multiple terminologies

---

mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/DataModelFunctionalSpec.groovy
mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/ReferenceDataModelFunctionalSpec.groovy
mdm-plugin-terminology/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/terminology/CodeSetFunctionalSpec.groovy
mdm-plugin-terminology/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/terminology/TerminologyFunctionalSpec.groovy

Handle the possibility that an unknown ID may be passed to the deletion endpoint.
Closes #257 
(Test failure on the branch not related)

gh-257 handle unknown IDs

---

mdm-plugin-referencedata/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValue.groovy
mdm-plugin-referencedata/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueFunctionalSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/referencedata/ReferenceDataValueFunctionalSpec.groovy

Closes #334  
Fix the constraint on ReferenceDataValue.
The existing constraint `value blank: true, nullable: true, unique: ['rowNumber', 'referenceDataElement']` meant 'value must be unique within rowNumber and referenceDataElement'
This has been changed to `rowNumber unique: 'referenceDataElement'`.
Modify and add tests accordingly.

Allow one ReferenceDataValue per ReferenceDataModel row and column

---

mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/UserGroupInterceptor.groovy
mdm-testing-functional/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/UserAccessAndPermissionChangingFunctionalSpec.groovy

Closes #256 
Fall back to using `securableResourceId` and add a test for the endpoint `GET /{securableResourceDomainType}/{securableResourceId}/groupRoles/{groupRoleId}/userGroups`

gh-256 use the securableResourceId

---

mdm-security/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/security/role/SecurableResourceGroupRoleController.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/role/SecurableResourceGroupRoleService.groovy
mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/role/SecurableResourceGroupRoleControllerSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/security/role/SecurableResourceGroupRoleFunctionalSpec.groovy
mdm-testing-functional/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/UserAccessFunctionalSpec.groovy
mdm-testing-functional/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/expectation/Expectations.groovy

Closes #254 
- Make a small fix to the SecurableResourceGroupRoleController and SecurableResourceGroupRoleService to allow the findSecurableResource method to return a null value rather than throw an exception. This fixes the original bug.
- As required by the ticket, also add E2E tests for SecurableResourceGroupRole. As I am not certain what the requirements are, the test expectations are set up to pass given the current implementation in code.
- One problem I did notice is that there seems to be no `/edits`endpoint for SecurableResourceGroupRole. To ensure that the test suite passes I've added a test expectation `hasEditsEndpoint` and used this to skip testing of edits for SecurableResourceGroupRole. If it is required to add an endpoint for retrieving edits then this could be raised as …

Feature/gh 254 Fix creation of SecurableResourceGroupRole on UserGroup endpoint

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/VersionedFolderService.groovy
mdm-core/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/VersionedFolderFunctionalSpec.groovy

Closes #330 
- add a failing test scenario to replicate the issue described in the ticket, i.e.
- create and finalise a VF at 1.0.0
- create and finalise a new version of the VF at 1.1.0
- create a new version of the VF
- delete version 1.0.0
- see that when selecting the main branch in the UI, the endpoint `${main version Id}/simpleModelVersionTree?branchesOnly=undefined` responds with a 500 internal server error
- fix the failing scenario by deleting version links which point to the deleted VF

Feature/gh 330 Delete version links when deleting a versioned folder

---

mdm-security/grails-app/conf/db/migration/security/V5_2_0__add_securableresourcegrouprole_constraint.sql

Closes #347 
To reproduce the problem described in the ticket I placed a debug breakpoint in the backend code; this gave me plenty of time to press the green tick and verify that indeed multiple request to create a SecurableResourceGroupRole do succeed.
After adding the database constraint I did the same again, and received a response of
```{"status":500,"reason":"Internal Server Error","errorCode":"UEX--","message":"ERROR: duplicate key value violates unique constraint \"ukfa251ce1f3b24cad8cccd15394d1\"\n  Detail: Key (securable_resource_id, user_group_id)=(77c43d51-9060-44e9-a987-6a8b2bdfaeb2, 0721a5da-812b-4cf6-828d-3078619ce667) already exists.","path":"/api/Folder/77c43d51-9060-44e9-a987-6a8b2bdfaeb2/groupRoles/83ab3977-841e-4307-b4d3-b16fe0a51511/userGroups/0721a5da-812b-4cf6-828d-30 …
```

gh-347 add a database constraint to prevent duplicate SecurableResourceGroupRole

---

mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemController.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/VersionedFolderService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemService.groovy
mdm-core/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/VersionedFolderServiceSpec.groovy
mdm-core/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/core/tree/TreeItemFunctionalSpec.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/tree/TreeItemServiceSpec.groovy

Resolves #288 
Update the tree endpoints, like `GET api/tree/folders/{id}` to use the provided `includeModelSuperseded` and `includeDeleted` parameters on Versioned Folders. By default Versioned Folders that are superseded are _not_ included in the tree response, unless `includeModelSuperseded=true` is provided.
Tests around the `VersionedFolderService` and `TreeItemService` have also been updated to test the behaviour.
This is my first PR to `mdm-core`, and also my first experience working in Groovy, so any feedback would be welcome.

gh-288 Update tree endpoints to filter superseded Versioned Folders

---

mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/path/PathController.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/async/AsyncJobService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/async/DomainExportService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/authority/AuthorityService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/VersionedFolderService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/AnnotationService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/MetadataService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/ReferenceFileService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/RuleService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/SemanticLinkService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/VersionLinkService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/facet/rule/RuleRepresentationService.groovy
mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/path/PathService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/CatalogueItemService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ContainerService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/service/MdmDomainService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/facet/SummaryMetadataService.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/facet/summarymetadata/SummaryMetadataReportService.groovy
mdm-plugin-referencedata/grails-app/services/uk/ac/ox/softeng/maurodatamapper/referencedata/facet/ReferenceSummaryMetadataService.groovy
mdm-plugin-referencedata/grails-app/services/uk/ac/ox/softeng/maurodatamapper/referencedata/facet/summarymetadata/ReferenceSummaryMetadataReportService.groovy
mdm-plugin-referencedata/grails-app/services/uk/ac/ox/softeng/maurodatamapper/referencedata/item/ReferenceDataValueService.groovy
mdm-plugin-terminology/grails-app/services/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermService.groovy
mdm-plugin-terminology/grails-app/services/uk/ac/ox/softeng/maurodatamapper/terminology/item/term/TermRelationshipService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/CatalogueUserService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/UserGroupService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/authentication/ApiKeyService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/role/GroupRoleService.groovy
mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/role/SecurableResourceGroupRoleService.groovy

gh-363 Provide a path in the API to view the latest finalised datamodel
eg. http://localhost:8080/api/dataModels/path/dm:DM_LABEL?finalised=true

gh-363 request param to select finalized models by label

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/container/ClassifierService.groovy
mdm-core/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/core/container/ClassifierServiceSpec.groovy

gh-371 The get classifier elements endpoint was updated to include filtering by label, description and domain type

gh-371 Add filtering to get classifier element API call

---

mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/traits/domain/IndexedSiblingAware.groovy
mdm-testing-framework/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/test/functional/OrderedResourceFunctionalSpec.groovy

When reordering a ModelItem in a collection, take into account the direction in which the ModelItem is moved when reordering the siblings. Add a test for this. Resolves #367.

Handle reordering of ModelItems depending on direction of reordering

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/importer/ImporterService.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/model/ModelService.groovy

Don't revalidate model when imported from a provider which sets `providerHasSavedModels = true`.
When `providerHasSavedModels` is set the importer provider service should:
- Do all validation of the model
- Do all saving of the model
- Set any additional properties from the importer parameters, e.g. the folderId, itself.

Check providerHasSavedModels parameter in async Model importer job

---

mdm-plugin-datamodel/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/datamodel/facet/SummaryMetadata.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/facet/SummaryMetadataService.groovy
mdm-plugin-datamodel/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/datamodel/test/functional/CatalogueItemSummaryMetadataFunctionalSpec.groovy

Also created tests for filtering/sorting summaryMetadata.
Following endpoints now supported:
```
GET /{domainType}/{id}/summaryMetadata?label=<value>
GET /{domainType}/{id}/summaryMetadata?sort=label&order=desc
```
Fixes #389

gh-389 Update SummaryMetadata to support filtering for index queries

---

mdm-common/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/util/Utils.groovy
mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataElementService.groovy
mdm-plugin-terminology/grails-app/services/uk/ac/ox/softeng/maurodatamapper/terminology/item/TermService.groovy

Fixes #354 by breaking large delete statements into smaller ones.  This means that the error: `Tried to send an out-of-range integer as a 2-byte value` doesn't get thrown and the database connection doesn't get closed.  Some details here: https://github.com/pgjdbc/pgjdbc/issues/1311.

Add batching to potentially large deletion operations

---

mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/admin/ApiPropertyService.groovy
mdm-core/grails-app/views/error.gson
mdm-core/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/core/admin/ApiPropertyFunctionalSpec.groovy
mdm-core/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/core/admin/ApiPropertyEnum.groovy
mdm-security/grails-app/views/error.gson
mdm-security/src/test/groovy/uk/ac/ox/softeng/maurodatamapper/security/CatalogueUserControllerSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/core/admin/ApiPropertyFunctionalSpec.groovy
mdm-testing-functional/src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/testing/functional/core/error/ErrorFunctionalSpec.groovy

Resolves #381.
If ApiProperty `security.hide.exception` is present and set to true, exception stack traces, internal error codes and error messages are hidden. If not set, exceptions are shown as normal. This setting doesn't affect Grails validation errors, for example "field is required" messages.

Add new ApiProperty to disable revealing exceptions in error messages
